import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Setlayout } from "../components/Setlayout";
import { Toaster } from "sonner";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Setlayout>{children}</Setlayout>
        <Toaster position="bottom-center" richColors />
      </body>
    </html>
  );
}
